### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by mk-pmb** [kba/anno-common#75]
Hi! What's the license status of the files in this project? I assume all MIT? Could you declare that, and your preferred attribution (e.g. author name), in package.json and maybe also in a LICENSE.txt?

**Comment by kba** [comment]
MIT is fine, `LICENSE` file added. Let me know if you're using this somewhere (not because of the license, obviously, I'm just curious)

**Comment by mk-pmb** [comment]
Thanks! :+1:
