### ISSUE TITLE
Arrow functions defined by code blocks that return object literals

### ISSUE THREAD

**Issue by mk-pmb** [kba/anno-common#77]
Hi! I found some return statements that I don't understand:

```javascript
// anno-queries/anno2heiper.js:30:
      creators: ensureArray(anno, 'creator').map(c => {return {

// anno-store-sql/transform.js:91:
    if ('type' in anno) sqlRev.type = anno.type.map(t => {return {_id: t}})

// anno-test/middlewares.test.js:15:
    const asAnonymous = () => {return {}}
    const asAdmin = () => {return {user:'admin-user'}}
```

They're all of the form

```javascript
(...args) => {return { /* object literal */ }}
```

which to me looks like it should be equivalent to

```javascript
(...args) => ({ /* object literal */ })
```

Is it just a stylistic choice (and safe to convert) or are there subtle differences when using a code block to define the arrow function?

**Comment by kba** [comment]
> Is it just a stylistic choice (and safe to convert) or are there subtle differences when using a code block to define the arrow function?

It wasn't even a stylistic choice, I think this was due to one of the browsers not supporting the latter syntax. I think these are equivalent and if it's supported in all browsers/Node.JS versions: go for it.

**Comment by mk-pmb** [comment]
Thanks for that important warning! I'll make sure to have proper browser tests on CI before trying to convert it.
